### ISSUE TITLE
make it easy to share current map position

### ISSUE THREAD

**Issue by AntoJvlt** [osm-search/Nominatim-Data-Analyser-Frontend#1]
Osmoscope adds URL fragments with current map position and zoom whenever one moves the map, e.g. #map=17.991666666666667/6.8867/52.24745 This makes it easy to share the current view with other users.

**Comment by lonvia** [comment]
It would be good in general, when a reload of the page keeps the current state of view. This is needed to get new data, when the vector tiles have changed.

**Comment by AntoJvlt** [comment]
Please @lonvia can you check on https://gsoc2021-qa.nominatim.org/front if this what you expected with your last comment please? The state is stored and retrieved when reloading the page.

I will wait your confirmation to merge #8.
