### ISSUE TITLE
Ignore non-existent layers

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim-Data-Analyser-Frontend#10]
The site fails to load when one of the layer description files cannot be found. It would be nice, if it just shows a warning and loads the other layers anyways.

**Comment by AntoJvlt** [comment]
This comes from the lack of CORS header for the 404 response returned by the server. So fetch is not able to accept the response and it crashes, I need to find a solution to prevent this on the front side.

**Comment by lonvia** [comment]
Interesting. I saw the CORS errors but thought they don't matter. In any case, I switched the server to send CORS also with 404 responses. Turns out to be [easy with nginx](https://serverfault.com/questions/393532/allowing-cross-origin-requests-cors-on-nginx-for-404-responses).
