### ISSUE TITLE
link correct repository on published website

### ISSUE THREAD

**Issue by matkoniecz** [osm-search/Nominatim-Data-Analyser-Frontend#19]
https://nominatim.org/qa/#map=2.91/0.00/0.00 links https://github.com/AntoJvlt/Nominatim-Data-Analyser/issues that redirects to https://github.com/AntoJvlt/Nominatim-Data-Analyser/pulls

>  please come to the "Issues" section of the github repository to discuss this.

Linking issues and mentioning issues in repo with disabled issues seem not intentional

**Comment by AntoJvlt** [comment]
I close this as it was fixed in the Svelte version.
