### ISSUE TITLE
Page does not always load correctly on first try

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim-Data-Analyser-Frontend#2]
When going to the page, it sometimes shows text place holders at the place of the arrow and cross icons and the layer list has the wrong format. This looks like a race condition when some of the resources takes to long to read. The behaviour is unfortunately not reproducable but I've seen it a couple of times now.

**Comment by AntoJvlt** [comment]
What browser are you using when experiencing this behavior?

**Comment by lonvia** [comment]
Firefox 78.13 on Linux.

**Comment by lonvia** [comment]
Hmm, it is reproducible. Always happens when loading the page for the first time after starting Firefox. There is no issue with Chromium.

**Comment by AntoJvlt** [comment]
I tried to reproduce on my ubuntu and on my windows with firefox and I can't. I also tried to downgrade to firefox 78.13 and it doesn't change anything.

This is really weird especially because the layer list is only displayed when all the json layers have been loaded.

**Comment by lonvia** [comment]
I've tried in safe mode to make sure it isn't an issue with the extensions but the issue shows up there, too, although less reliably. To make debugging more fun, it won't appear when the debug console is open. Maybe it's a react bug.

Now that I know how to reproduce it, I can offer a screenshot:

![broken_frontend](https://user-images.githubusercontent.com/1447941/131692846-d642b0ff-c7ee-48b0-be79-cc677ba0b1f6.png)

Reloading always fixes the issue.

**Comment by lonvia** [comment]
The issue is gone now. Not sure if a Firefox update did the trick or one of the recent commits. I'll close this for now.
