### ISSUE TITLE
fix Firefox issue

### ISSUE THREAD

**Issue by matkoniecz** [osm-search/Nominatim-Data-Analyser-Frontend#20]
> You might encounter some performance issues with some layers if you are using the Firefox browser. Please switch to another browser if this is the case.

What is going on? I see no open issue for that - is it a Firefox bug? Upstream bug? It would be nice to link it so I can at least go there and upvote the issue.

**Comment by lonvia** [comment]
Is that still in? @AntoJvlt I think that can be safely deleted. Firefox is doing fine.

**Comment by matkoniecz** [comment]
If just removal of warning is needed then merging #21 will end the problem.
